FROM jetadmin/jetbridge:latest

ENV JET_PROJECT=${JET_PROJECT}
ENV JET_DATABASE_ENGINE=${JET_DATABASE_ENGINE}
ENV JET_DATABASE_HOST=${JET_DATABASE_HOST}
ENV JET_DATABASE_PORT=${JET_DATABASE_PORT}
ENV JET_DATABASE_NAME=${JET_DATABASE_NAME}
ENV JET_DATABASE_USER=${JET_DATABASE_USER}
ENV JET_DATABASE_PASSWORD=${JET_DATABASE_PASSWORD}

EXPOSE 8888

ENTRYPOINT ["jet_bridge", "start"]
