#!/bin/sh

export JET_PROJECT="$JET_PROJECT"
export JET_DATABASE_ENGINE="$JET_DATABASE_ENGINE"
export JET_DATABASE_HOST="$JET_DATABASE_HOST"
export JET_DATABASE_PORT="$JET_DATABASE_PORT"
export JET_DATABASE_NAME="$JET_DATABASE_NAME"
export JET_DATABASE_USER="$JET_DATABASE_USER"
export JET_DATABASE_PASSWORD="$JET_DATABASE_PASSWORD"

jet_bridge start
