# Generated by Django 6.0.2 on 2026-03-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tamano', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategoria', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_importacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_general', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_mercado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ganancia_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagen_principal', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_secundaria', models.URLField(blank=True, max_length=500, null=True)),
                ('imagen_terciaria', models.URLField(blank=True, max_length=500, null=True)),
                ('destacado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria')),
            ],
        ),
    ]
