# Generated by Django 6.0.3 on 2026-06-21 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='inventario.categoria')),
            ],
            options={
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificacion_katy', models.BooleanField(default=False)),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('tamano', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('costo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_importacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_mercado_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('valor_total_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_general', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia_unidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_soles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ventas_totales', models.IntegerField(default=0)),
                ('busquedas_totales', models.IntegerField(default=0)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_calificaciones', models.IntegerField(default=0)),
                ('imagen_principal', models.BinaryField(blank=True, null=True)),
                ('imagen_principal_mime', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_secundaria', models.BinaryField(blank=True, null=True)),
                ('imagen_secundaria_mime', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen_terciaria', models.BinaryField(blank=True, null=True)),
                ('imagen_terciaria_mime', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventario.subcategoria')),
            ],
        ),
    ]
