# Generated by Django 6.0.2 on 2026-03-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='busquedas_totales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='calificacion_promedio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='total_calificaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='ventas_totales',
            field=models.IntegerField(default=0),
        ),
    ]
