# Generated by Django 6.0.3 on 2026-06-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_recreate_subcategoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoria',
            options={'verbose_name': 'Subcategoría', 'verbose_name_plural': 'Subcategorías'},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_secundaria_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_terciaria_mime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_secundaria',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_terciaria',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('categoria', 'nombre')},
        ),
    ]
