# Generated by Django 6.0.3 on 2026-06-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_subcategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='verificacion_katy',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
