# Generated by Django 6.0.2 on 2026-04-02 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=10)),
                ('metodo', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('yape', 'Yape')], default='paypal', max_length=20)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='CREADA', max_length=20)),
                ('carrito', models.JSONField(default=dict)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
